### ISSUE TITLE
ZeroDivisionError: float division by zero in Python UWG code

### ISSUE THREAD

**Issue by canafarci** [ladybug-tools/uwg#247]
Hello, when i try to run UWG i've encountered an error building.py,

Traceback (most recent call last):
  File "e:/ARCHIVE/BAP/uwg/Scripts/20_06_21-BC-UWG-BAP copy.py", line 89, in <module>
    custom_uwg(sample_directory)
  File "e:/ARCHIVE/BAP/uwg/Scripts/20_06_21-BC-UWG-BAP copy.py", line 77, in custom_uwg
    model.simulate()
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python37\lib\site-packages\uwg\uwg.py", line 1350, in simulate
    self.RSM)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python37\lib\site-packages\uwg\urbflux.py", line 38, in urbflux
    BEM[j].building.BEMCalc(UCM, BEM[j], forc, parameter, simTime)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python37\lib\site-packages\uwg\building.py", line 462, in BEMCalc
    (dens * parameter.cp * (T_indoor - 283.15))
ZeroDivisionError: float division by zero

Error seems to be happening because of `dens `variable which is "Moist air density given dry bulb temp, humidity ratio, and pressure", where while calculating it in psychrometrics.py, the lines 

`def moist_air_density(P, Tdb, H):
    return P / (1000 * 0.287042 * Tdb * (1. + 1.607858 * H))`

returns zero, because H value which represents "Number for Humidity Ratio (kgv/kgda)" becomes a very big bumber and python prints it as inf (before that it reaches 10e194ish numbers) 

H value is entered in building.py to calculate dens value, in BEMCalc function. (`dens = moist_air_density(forc.pres, self.indoor_temp, self.indoor_hum)  # kgv/m3` ), H here corrensponds to "self.indoor_hum", which is also calculated later in the building.py function, `self.indoor_hum = (self.indoor_hum + (simTime.dt / (dens * parameter.lv * UCM.bldHeight)) * (QLintload + QLinfil + QLvent - Qdehum))`,

  this function fails because of the sharp changes in `parameter.lv` value which is "latent heat of evaporation [J kgv-1]" . However, , could not find the exact reason why `parameter.lv` value's incorrect calculation, as i couldn't find where it was set.

   Thanks for your reply, have a nice day!

**Comment by saeranv** [comment]
@canafarci  the latent heat of evaporation is a constant, so it shouldn't be changing.  

Can you provide the epw and input files you are using so I can try to reproduce it on my end?

**Comment by canafarci** [comment]
Of course,

EPW i have used is [here,](https://energyplus.net/weather-location/europe_wmo_region_6/TUR//TUR_Ankara.171280_IWEC) it is from Ankara, Turkey

and the scipt i have used is [this, ](https://github.com/canafarci/MARCH_Repo/blob/main/venv/22_06_21-BC-UWG-SIM.py), on my end i receive the above mentioned error on day 87

**Comment by saeranv** [comment]
@canafarci 

The problem does lie with the `indoor_hum`, but it's not because of the latent heat of evaporation (is a constant), it's because the calculated latent impact of dehumidification is compounding because the sensible cooling demand larger then the cooling capacity of your hvac system and targetting an indoor air temperature below the cooling supply air temperature. 

All of this is because of the schedules you're defining in your script for the cooling and heating setpoints:

```
    default_week = [[0.15] * 24] * 3
    
    schdef1 = SchDef(elec=default_week, gas=default_week, light=default_week,
                     occ=default_week, cool=default_week, heat=default_week,
                     swh=default_week, q_elec=18.9, q_gas=3.2, q_light=18.9,
                     n_occ=0.12, vent=0.0013, v_swh=0.2846, bldtype='midriseapartment',
                     builtera='new')
```
According to this, the cooling and heating setpoints are 0.15C. Both heating and cooling seasons thus attempt to mechanically condition the indoor air to an extremely low temperature. This isn't a problem during the heating season since UWG simply adds the appropriate (efficiency-adjusted) heat energy to the zone thermal balance and ignores any energy associated with dehumidification. But once the cooling season starts (day 87), the dehumidification demand is calculated and conflicts with the way the UWG models cooling via an HVAC air system. Basically, the UWG attempts to calculate a supply airflow rate that can meet the cooling demand, and incorporates the dehumidification energy into the evolution of the indoor humidity, which is why we eventually get the error with the psychrometric calculations. 

On your end, you can fix this simply be fixing your setpoint temperatures (in Celsius) in your schedule. I realize this was likely copied from an example script I made, so fyi those values are dummy values for testing and aren't meant to represent real values. You can find real representative values in the DOE reference buildings include in UWG. 

I'm also going to add some checks in the code to make sure this doesn't happen again. I've already a numerical range check to the setpoint schedules, but I think I'll also raise an exception if the indoor temperature ever goes below the supply air temperature during the cooling demand calculations, since that breaks UWG's assumption that mechanical cooling is only used when indoor temperatures are above the supply air temperature (i.e. below that you get negative airflow rates, and humidity ratios), and there are a bunch of user-exposed parameters in the cooling demand calculation that can cause this behaviour again. I can't think of a similar threshold to use for the heating season, even though a ~0C heating setpoint doesn't make sense, technically nothing breaks the underlying physics assumptions, so I'll leave it as is.
